import {
  intro,
  outro,
  spinner,
  text,
  password as promptPassword,
  note,
  log,
  isCancel,
  cancel,
  confirm,
} from '@clack/prompts'
import { execa } from 'execa'
import { mkdirSync, writeFileSync, readFileSync, existsSync } from 'node:fs'
import { join } from 'node:path'
import { generateSecret } from '../utils/crypto.js'
import { renderEnvWeb } from '../templates/env-web.js'
import { renderEnvEngine } from '../templates/env-engine.js'
import { writeConfig } from '../utils/config.js'

interface DevConfig {
  adminEmail: string
  dbPassword: string
  redisPassword: string
  sessionSecret: string
  engineWebhookSecret: string
  internalApiKey: string
  sfdcClientId: string
  sfdcClientSecret: string
  sfdcLoginUrl: string
  engineTunnelUrl: string
}

function getDevDir(): string {
  return join(process.cwd(), 'lead-routing-dev')
}

function renderDevDockerCompose(dbPassword: string, redisPassword: string): string {
  return `# Lead Routing — Local Dev Docker Compose
# Generated by lead-routing dev — do not edit manually.

services:

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_DB: leadrouting
      POSTGRES_USER: leadrouting
      POSTGRES_PASSWORD: ${dbPassword}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U leadrouting"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --requirepass ${redisPassword}
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a ${redisPassword} ping | grep PONG"]
      interval: 5s
      timeout: 3s
      retries: 10

  web:
    image: ghcr.io/atgatzby/lead-routing-web:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
    env_file: .env.web
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://$(hostname -i):3000/api/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 6
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  engine:
    image: ghcr.io/atgatzby/lead-routing-engine:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:3001:3001"
    env_file: .env.engine
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://$(hostname -i):3001/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 6
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  postgres_data:
  redis_data:
`
}

function bail(value: unknown): never {
  if (isCancel(value)) {
    cancel('Setup cancelled.')
    process.exit(0)
  }
  throw new Error('Unexpected cancel')
}

async function pollHealth(url: string, attempts = 30, intervalMs = 3000): Promise<boolean> {
  for (let i = 0; i < attempts; i++) {
    try {
      const res = await fetch(url)
      if (res.ok) return true
    } catch {}
    await new Promise((r) => setTimeout(r, intervalMs))
  }
  return false
}

export async function runDev(opts: { reset?: boolean; logs?: string; sfdc?: boolean } = {}) {
  // ── Update SFDC credentials ─────────────────────────────────────────────────
  if (opts.sfdc) {
    const devDir = getDevDir()
    const configFile = join(devDir, 'dev.json')
    if (!existsSync(configFile)) {
      console.error('No dev environment found. Run `lead-routing dev` first.')
      process.exit(1)
    }
    intro('Lead Routing — Update Salesforce Credentials')

    note(
      'You need a Salesforce Connected App with callback URL:\n' +
        '  http://localhost:3000/api/auth/sfdc/callback',
      'Before you begin'
    )

    const clientId = await text({
      message: 'Consumer Key (Client ID)',
      validate: (v) => (!v ? 'Required' : undefined),
    })
    if (isCancel(clientId)) { cancel('Cancelled.'); process.exit(0) }

    const clientSecret = await promptPassword({ message: 'Consumer Secret' })
    if (isCancel(clientSecret)) { cancel('Cancelled.'); process.exit(0) }

    const loginUrl = await text({
      message: 'Login URL',
      initialValue: 'https://login.salesforce.com',
      validate: (v) => (!v ? 'Required' : undefined),
    })
    if (isCancel(loginUrl)) { cancel('Cancelled.'); process.exit(0) }

    // Update .env.web
    const envPath = join(devDir, '.env.web')
    const lines = readFileSync(envPath, 'utf8').split('\n')
    const updates: Record<string, string> = {
      SFDC_CLIENT_ID: (clientId as string).trim(),
      SFDC_CLIENT_SECRET: (clientSecret as string).trim(),
      SFDC_LOGIN_URL: (loginUrl as string).trim(),
      SFDC_REDIRECT_URI: 'http://localhost:3000/api/auth/sfdc/callback',
    }
    const updated = new Set<string>()
    const result = lines.map((line) => {
      const eq = line.indexOf('=')
      if (eq === -1) return line
      const key = line.slice(0, eq)
      if (key in updates) { updated.add(key); return `${key}=${updates[key]}` }
      return line
    })
    for (const [k, v] of Object.entries(updates)) {
      if (!updated.has(k)) result.push(`${k}=${v}`)
    }
    writeFileSync(envPath, result.join('\n'), 'utf8')

    // Update dev.json
    const cfg = JSON.parse(readFileSync(configFile, 'utf8')) as DevConfig
    cfg.sfdcClientId = (clientId as string).trim()
    cfg.sfdcClientSecret = (clientSecret as string).trim()
    cfg.sfdcLoginUrl = (loginUrl as string).trim()
    writeFileSync(configFile, JSON.stringify(cfg, null, 2), 'utf8')

    log.success('Credentials saved')

    // Restart web container to pick up new env
    const s = spinner()
    s.start('Restarting web container...')
    await execa('docker', ['compose', 'restart', 'web'], { cwd: devDir, stdio: 'ignore' })
    s.stop('Web container restarted')

    outro('Done! Connect Salesforce at http://localhost:3000/integrations/salesforce')
    return
  }

  // ── Stream logs subcommand ──────────────────────────────────────────────────
  if (opts.logs !== undefined) {
    const service = opts.logs || 'engine'
    const devDir = getDevDir()
    if (!existsSync(join(devDir, 'docker-compose.yml'))) {
      console.error('No dev environment found. Run `lead-routing dev` first.')
      process.exit(1)
    }
    const valid = ['web', 'engine', 'postgres', 'redis']
    if (!valid.includes(service)) {
      console.error(`Unknown service "${service}". Valid: ${valid.join(', ')}`)
      process.exit(1)
    }
    await execa('docker', ['compose', 'logs', '-f', '--tail=100', service], {
      cwd: devDir,
      stdio: 'inherit',
    })
    return
  }

  intro('Lead Routing — Local Dev')

  // ── Check Docker is running ─────────────────────────────────────────────────
  try {
    await execa('docker', ['info'], { stdio: 'ignore' })
  } catch {
    log.error('Docker is not running. Please start Docker Desktop and try again.')
    process.exit(1)
  }

  const devDir = getDevDir()
  const configFile = join(devDir, 'dev.json')
  const isFirstRun = !existsSync(configFile)
  let cfg: DevConfig
  let adminPassword = ''

  if (!isFirstRun && !opts.reset) {
    // ── Returning run — just restart services ─────────────────────────────────
    cfg = JSON.parse(readFileSync(configFile, 'utf8')) as DevConfig
    log.info('Existing dev environment found — starting services...')
  } else {
    // ── First-time setup or --reset ───────────────────────────────────────────
    if (opts.reset && !isFirstRun) {
      const ok = await confirm({
        message: 'This will wipe all local dev data (database, redis). Continue?',
      })
      if (isCancel(ok) || !ok) {
        cancel('Reset cancelled.')
        process.exit(0)
      }
      const s = spinner()
      s.start('Stopping and removing volumes...')
      try {
        await execa('docker', ['compose', 'down', '-v'], { cwd: devDir, stdio: 'ignore' })
      } catch {}
      s.stop('Volumes removed')
    }

    note(
      'Sets up a full Lead Routing stack locally using Docker.\n' +
        'No SSH, no VPS, no manual steps.',
      'First-time setup'
    )

    // Admin account
    const adminEmail = await text({
      message: 'Admin email',
      placeholder: 'you@company.com',
      validate: (v) => {
        if (!v) return 'Required'
        if (!v.includes('@')) return 'Must be a valid email'
      },
    })
    if (isCancel(adminEmail)) bail(adminEmail)

    const pw = await promptPassword({
      message: 'Admin password (min 8 characters)',
      validate: (v) => {
        if (!v) return 'Required'
        if (v.length < 8) return 'Must be at least 8 characters'
      },
    })
    if (isCancel(pw)) bail(pw)
    adminPassword = pw as string

    // Salesforce (optional)
    note(
      'Optional — needed to connect Salesforce.\nPress Enter to skip; add credentials later via `lead-routing config sfdc`.',
      'Salesforce Connected App'
    )

    const sfdcClientId = await text({
      message: 'Consumer Key (Client ID)',
      placeholder: 'Leave blank to skip',
    })
    if (isCancel(sfdcClientId)) bail(sfdcClientId)

    let sfdcClientSecret = ''
    if ((sfdcClientId as string)?.trim()) {
      const s = await promptPassword({ message: 'Consumer Secret' })
      if (isCancel(s)) bail(s)
      sfdcClientSecret = (s as string).trim()
    }

    // Engine tunnel (optional)
    const tunnelUrl = await text({
      message: 'Engine tunnel URL (for Salesforce webhooks)',
      placeholder: 'Leave blank — use `ssh -R 80:localhost:3001 localhost.run` to get one',
    })
    if (isCancel(tunnelUrl)) bail(tunnelUrl)

    cfg = {
      adminEmail: (adminEmail as string).trim(),
      dbPassword: generateSecret(16),
      redisPassword: generateSecret(16),
      sessionSecret: generateSecret(32),
      engineWebhookSecret: generateSecret(32),
      internalApiKey: generateSecret(32),
      sfdcClientId: (sfdcClientId as string)?.trim() ?? '',
      sfdcClientSecret,
      sfdcLoginUrl: 'https://login.salesforce.com',
      engineTunnelUrl: (tunnelUrl as string)?.trim() ?? '',
    }

    // Generate files
    mkdirSync(devDir, { recursive: true })

    const dbUrl = `postgresql://leadrouting:${cfg.dbPassword}@postgres:5432/leadrouting`
    const redisUrl = `redis://:${cfg.redisPassword}@redis:6379`
    const publicEngineUrl = cfg.engineTunnelUrl || 'http://localhost:3001'

    writeFileSync(
      join(devDir, 'docker-compose.yml'),
      renderDevDockerCompose(cfg.dbPassword, cfg.redisPassword),
      'utf8'
    )

    const envWebBase = renderEnvWeb({
      appUrl: 'http://localhost:3000',
      engineUrl: 'http://engine:3001',
      publicEngineUrl,
      databaseUrl: dbUrl,
      redisUrl,
      sessionSecret: cfg.sessionSecret,
      engineWebhookSecret: cfg.engineWebhookSecret,
      adminEmail: cfg.adminEmail,
      adminPassword,
      internalApiKey: cfg.internalApiKey,
      licenseKey: undefined,
      licenseTier: 'pro',
    })

    writeFileSync(
      join(devDir, '.env.web'),
      envWebBase +
        `\n# Salesforce Connected App\nSFDC_CLIENT_ID=${cfg.sfdcClientId}\nSFDC_CLIENT_SECRET=${cfg.sfdcClientSecret}\nSFDC_REDIRECT_URI=http://localhost:3000/api/auth/sfdc/callback\nSFDC_LOGIN_URL=${cfg.sfdcLoginUrl}\n`,
      'utf8'
    )

    writeFileSync(
      join(devDir, '.env.engine'),
      renderEnvEngine({
        databaseUrl: dbUrl,
        redisUrl,
        engineWebhookSecret: cfg.engineWebhookSecret,
        internalApiKey: cfg.internalApiKey,
        licenseKey: undefined,
        licenseTier: 'pro',
      }),
      'utf8'
    )

    // Save dev.json (no admin password stored)
    writeFileSync(configFile, JSON.stringify(cfg, null, 2), 'utf8')

    // Write lead-routing.json so `lead-routing sfdc deploy` works as-is
    writeConfig(devDir, {
      appUrl: 'http://localhost:3000',
      engineUrl: publicEngineUrl,
      installDir: devDir,
      remoteDir: devDir,
      ssh: { host: 'localhost', port: 22, username: 'local' },
      dockerManaged: { db: true, redis: true },
      engineWebhookSecret: cfg.engineWebhookSecret,
      licenseTier: 'pro',
      installedAt: new Date().toISOString(),
      version: '0.0.0',
    })

    log.success('Generated config files in ./lead-routing-dev/')
  }

  // ── Pull latest images ──────────────────────────────────────────────────────
  const pullS = spinner()
  pullS.start('Pulling latest images...')
  try {
    await execa('docker', ['compose', 'pull'], { cwd: devDir, stdio: 'ignore' })
    pullS.stop('Images up to date')
  } catch {
    pullS.stop('Using cached images')
  }

  // ── Start services ──────────────────────────────────────────────────────────
  const startS = spinner()
  startS.start('Starting services...')
  try {
    await execa('docker', ['compose', 'up', '-d', '--remove-orphans'], {
      cwd: devDir,
      stdio: 'ignore',
    })
    startS.stop('Services started')
  } catch (err: unknown) {
    startS.stop('Failed to start services')
    log.error(err instanceof Error ? err.message : String(err))
    process.exit(1)
  }

  // ── Health checks ───────────────────────────────────────────────────────────
  const healthS = spinner()
  healthS.start('Waiting for web app...')
  const webOk = await pollHealth('http://localhost:3000/api/health')
  if (!webOk) {
    healthS.stop('Web app did not start in time')
    log.warn('Run `lead-routing dev logs web` to diagnose.')
    process.exit(1)
  }
  healthS.stop('Web app ready')

  const engineS = spinner()
  engineS.start('Waiting for engine...')
  const engineOk = await pollHealth('http://localhost:3001/health')
  engineS.stop(engineOk ? 'Engine ready' : 'Engine slow to start (check: lead-routing dev logs engine)')

  note(
    `  Web:    http://localhost:3000\n` +
      `  Engine: http://localhost:3001\n\n` +
      `  Login:  ${cfg.adminEmail}`,
    '✓ Lead Routing running locally'
  )

  if (cfg.sfdcClientId) {
    if (cfg.engineTunnelUrl) {
      log.info('Next: run `lead-routing sfdc deploy` to deploy the Salesforce package (same as prod)')
    } else {
      log.warn(
        'No engine tunnel URL set — Salesforce cannot reach localhost:3001.\n' +
          'To get a tunnel:  ssh -R 80:localhost:3001 localhost.run\n' +
          'Then re-run:      lead-routing dev --reset  (to update the tunnel URL)\n' +
          'Then deploy:      lead-routing sfdc deploy'
      )
    }
  } else {
    log.info('No Salesforce creds set. Add via: lead-routing dev --sfdc')
  }

  outro('Run `lead-routing dev logs` to stream logs  •  `lead-routing dev --reset` to wipe and restart')
}
