export interface CaddyConfig {
  appUrl: string
  engineUrl: string
  baseDomain?: string
  langfuseUrl?: string
  mcpEnabled?: boolean
  mcpUrl?: string
}

/**
 * Generates a Caddyfile for auto-HTTPS via Let's Encrypt.
 *
 * When baseDomain is provided, generates subdomain blocks for all services.
 * Falls back to legacy behaviour (separate app/engine URLs) for backwards compat.
 */
export function renderCaddyfile(config: CaddyConfig): string
/** @deprecated Use object overload */
export function renderCaddyfile(appUrl: string, engineUrl: string, langfuseUrl?: string): string
export function renderCaddyfile(appUrlOrConfig: string | CaddyConfig, engineUrl?: string, langfuseUrl?: string): string {
  let config: CaddyConfig
  if (typeof appUrlOrConfig === 'string') {
    config = { appUrl: appUrlOrConfig, engineUrl: engineUrl!, langfuseUrl }
  } else {
    config = appUrlOrConfig
  }

  const appHost = new URL(config.appUrl).hostname
  const engineParsed = new URL(config.engineUrl)
  const engineHost = engineParsed.hostname
  const enginePort = engineParsed.port // e.g. "3001" or "" if standard port

  let langfuseHostname = ''
  if (config.langfuseUrl) {
    try { langfuseHostname = new URL(config.langfuseUrl).hostname } catch { /* ignore */ }
  }

  let mcpHostname = ''
  if (config.mcpEnabled && config.mcpUrl) {
    try { mcpHostname = new URL(config.mcpUrl).hostname } catch { /* ignore */ }
  }

  const header = [
    `# Lead Routing — Caddyfile`,
    `# Generated by lead-routing CLI`,
    `# Caddy auto-provisions SSL certificates via Let's Encrypt`,
    ``,
    `(security_headers) {`,
    `  header {`,
    `    X-Content-Type-Options nosniff`,
    `    X-Frame-Options DENY`,
    `    Referrer-Policy strict-origin-when-cross-origin`,
    `    Permissions-Policy interest-cohort=()`,
    `    Strict-Transport-Security "max-age=31536000; includeSubDomains"`,
    `  }`,
    `}`,
  ]

  const appBlock = [
    ``,
    `${appHost} {`,
    `  import security_headers`,
    `  reverse_proxy web:3000 {`,
    `    health_uri /api/health`,
    `    health_interval 15s`,
    `  }`,
    `}`,
  ]

  // Port-based engine URL (e.g. https://acme.com:3001) vs subdomain (e.g. https://api.acme.com)
  const engineAddress = engineHost === appHost && enginePort
    ? `${engineHost}:${enginePort}`
    : engineHost

  const engineBlock = [
    ``,
    `${engineAddress} {`,
    `  import security_headers`,
    `  reverse_proxy engine:3001 {`,
    `    health_uri /health`,
    `    health_interval 15s`,
    `  }`,
    `}`,
  ]

  const langfuseBlock = langfuseHostname
    ? [
        ``,
        `${langfuseHostname} {`,
        `  import security_headers`,
        `  reverse_proxy langfuse:3000`,
        `}`,
      ]
    : []

  const mcpBlock = mcpHostname
    ? [
        ``,
        `${mcpHostname} {`,
        `  import security_headers`,
        `  reverse_proxy mcp:3100`,
        `}`,
      ]
    : []

  const marketingBlock = [
    ``,
    `# Marketing site — served independently`,
    `openedgeai.tech {`,
    `  import security_headers`,
    `  root * /srv/marketing-site`,
    `  file_server`,
    `  try_files {path} /index.html`,
    `}`,
  ]

  return [
    ...header,
    ...appBlock,
    ...engineBlock,
    ...langfuseBlock,
    ...mcpBlock,
    ...marketingBlock,
  ].join('\n')
}
