/**
 * Generates a Caddyfile for auto-HTTPS via Let's Encrypt.
 *
 * Case A — engine is a subdomain (engine.acme.com):
 *   Two separate site blocks, each get their own cert.
 *
 * Case B — engine is same domain + port (acme.com:3001):
 *   Caddy listens on two ports for the same hostname, reusing the cert.
 */
export function renderCaddyfile(appUrl: string, engineUrl: string): string {
  const appHost = new URL(appUrl).hostname
  const engineParsed = new URL(engineUrl)
  const engineHost = engineParsed.hostname
  const enginePort = engineParsed.port // e.g. "3001" or "" if standard port

  const isSameDomain = engineHost === appHost

  if (isSameDomain && enginePort) {
    // Case B: same domain, port-based engine URL (e.g. https://acme.com:3001)
    return [
      `# Lead Routing — Caddyfile`,
      `# Generated by lead-routing CLI`,
      `# Caddy auto-provisions SSL certificates via Let's Encrypt`,
      ``,
      `${appHost} {`,
      `  reverse_proxy web:3000 {`,
      `    health_uri /api/health`,
      `    health_interval 15s`,
      `  }`,
      `}`,
      ``,
      `${appHost}:${enginePort} {`,
      `  reverse_proxy engine:3001 {`,
      `    health_uri /health`,
      `    health_interval 15s`,
      `  }`,
      `}`,
    ].join('\n')
  }

  // Case A: subdomain-based engine URL (e.g. https://engine.acme.com)
  return [
    `# Lead Routing — Caddyfile`,
    `# Generated by lead-routing CLI`,
    `# Caddy auto-provisions SSL certificates via Let's Encrypt`,
    ``,
    `${appHost} {`,
    `  reverse_proxy web:3000 {`,
    `    health_uri /api/health`,
    `    health_interval 15s`,
    `  }`,
    `}`,
    ``,
    `${engineHost} {`,
    `  reverse_proxy engine:3001 {`,
    `    health_uri /health`,
    `    health_interval 15s`,
    `  }`,
    `}`,
  ].join('\n')
}
