export interface ComposeConfig {
  managedDb: boolean
  managedRedis: boolean
  dbPassword?: string
  webPort?: number
  enginePort?: number
}

export function renderDockerCompose(c: ComposeConfig): string {
  const webPort = c.webPort ?? 3000
  const enginePort = c.enginePort ?? 3001
  const dbPassword = c.dbPassword ?? 'leadrouting'

  const postgresService = c.managedDb
    ? `
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_DB: leadrouting
      POSTGRES_USER: leadrouting
      POSTGRES_PASSWORD: ${dbPassword}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U leadrouting"]
      interval: 5s
      timeout: 5s
      retries: 10
`
    : ''

  const redisService = c.managedRedis
    ? `
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
`
    : ''

  const webDependsOn = buildDependsOn(c.managedDb, c.managedRedis)
  const engineDependsOn = buildDependsOn(c.managedDb, c.managedRedis)

  const webService = `
  web:
    image: ghcr.io/atgatzby/lead-routing-web:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:${webPort}:3000"
    env_file: .env.web
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://$(hostname -i):3000/api/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 6${webDependsOn}
`

  const engineService = `
  engine:
    image: ghcr.io/atgatzby/lead-routing-engine:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:${enginePort}:3001"
    env_file: .env.engine
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://$(hostname -i):3001/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 6${engineDependsOn}
`

  const caddyService = `
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web
      - engine
`

  const volumes = buildVolumes(c.managedDb, c.managedRedis)

  return [
    `# Lead Routing — Docker Compose`,
    `# Generated by lead-routing CLI on ${new Date().toISOString()}`,
    `# Do not edit manually — re-run \`lead-routing init\` to regenerate.`,
    ``,
    `services:`,
    postgresService.trimEnd(),
    redisService.trimEnd(),
    webService.trimEnd(),
    engineService.trimEnd(),
    caddyService.trimEnd(),
    volumes,
  ]
    .filter(Boolean)
    .join('\n')
}

function buildDependsOn(managedDb: boolean, managedRedis: boolean): string {
  const deps: string[] = []
  if (managedDb) deps.push('postgres')
  if (managedRedis) deps.push('redis')
  if (deps.length === 0) return ''
  return (
    '\n    depends_on:\n' +
    deps.map((d) => `      ${d}:\n        condition: service_healthy`).join('\n')
  )
}

function buildVolumes(managedDb: boolean, managedRedis: boolean): string {
  const vols: string[] = []
  if (managedDb) vols.push('  postgres_data:')
  if (managedRedis) vols.push('  redis_data:')
  vols.push('  caddy_data:')
  vols.push('  caddy_config:')
  return '\nvolumes:\n' + vols.join('\n')
}
