export interface ComposeConfig {
  managedDb: boolean
  managedRedis: boolean
  dbPassword?: string
  redisPassword?: string
  webPort?: number
  enginePort?: number
  managedLangfuse?: boolean
  langfuseUrl?: string
  langfuseSecret?: string
  langfuseSalt?: string
  managedMcp?: boolean
  mcpUrl?: string
  mcpAppUrl?: string
  mcpEngineUrl?: string
  mcpApiToken?: string
  mcpWebhookSecret?: string
  mcpCrmType?: string
}

export function renderDockerCompose(c: ComposeConfig): string {
  const webPort = c.webPort ?? 3000
  const enginePort = c.enginePort ?? 3001
  const dbPassword = c.dbPassword ?? 'leadrouting'

  const postgresService = c.managedDb
    ? `
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_DB: leadrouting
      POSTGRES_USER: leadrouting
      POSTGRES_PASSWORD: ${dbPassword}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U leadrouting"]
      interval: 5s
      timeout: 5s
      retries: 10
`
    : ''

  const redisPassword = c.redisPassword ?? ''
  const redisService = c.managedRedis
    ? `
  redis:
    image: redis:7-alpine
    restart: unless-stopped${redisPassword ? `\n    command: redis-server --requirepass ${redisPassword}` : ''}
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli${redisPassword ? ` -a ${redisPassword}` : ''} ping | grep PONG"]
      interval: 5s
      timeout: 3s
      retries: 10
`
    : ''

  const webDependsOn = buildDependsOn(c.managedDb, c.managedRedis)
  const engineDependsOn = buildDependsOn(c.managedDb, c.managedRedis)

  const webService = `
  web:
    image: ghcr.io/atgatzby/lead-routing-web:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:${webPort}:3000"
    env_file: .env.web
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://$(hostname -i):3000/api/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 6${webDependsOn}
`

  const engineService = `
  engine:
    image: ghcr.io/atgatzby/lead-routing-engine:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:${enginePort}:3001"
    env_file:
      - .env.engine
      - .env.web
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://$(hostname -i):3001/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 6${engineDependsOn}
`

  const langfuseService = c.managedLangfuse
    ? `
  langfuse:
    image: langfuse/langfuse:2
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://leadrouting:${dbPassword}@postgres:5432/langfuse
      NEXTAUTH_URL: ${c.langfuseUrl ?? ''}
      NEXTAUTH_SECRET: ${c.langfuseSecret ?? ''}
      SALT: ${c.langfuseSalt ?? ''}
      TELEMETRY_ENABLED: "false"
      HOSTNAME: "0.0.0.0"
      PORT: "3000"
    depends_on:
      postgres:
        condition: service_healthy
`
    : ''

  const mcpService = c.managedMcp
    ? `
  mcp:
    image: ghcr.io/atgatzby/lead-routing-mcp:latest
    restart: unless-stopped
    environment:
      APP_URL: ${c.mcpAppUrl ?? 'http://web:3000'}
      ENGINE_URL: ${c.mcpEngineUrl ?? 'http://engine:3001'}
      API_TOKEN: ${c.mcpApiToken ?? ''}
      WEBHOOK_SECRET: ${c.mcpWebhookSecret ?? ''}
      CRM_TYPE: ${c.mcpCrmType ?? 'salesforce'}
      MCP_PUBLIC_URL: ${c.mcpUrl ?? ''}
      PORT: "3100"
      TRANSPORT: http
    depends_on:
      web:
        condition: service_healthy
`
    : ''

  const caddyDeps = ['web', 'engine']
  if (c.managedLangfuse) caddyDeps.push('langfuse')
  if (c.managedMcp) caddyDeps.push('mcp')

  const caddyService = `
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
${caddyDeps.map((d) => `      - ${d}`).join('\n')}
`

  const volumes = buildVolumes(c.managedDb, c.managedRedis)

  return [
    `# Lead Routing — Docker Compose`,
    `# Generated by lead-routing CLI on ${new Date().toISOString()}`,
    `# Do not edit manually — re-run \`lead-routing init\` to regenerate.`,
    ``,
    `services:`,
    postgresService.trimEnd(),
    redisService.trimEnd(),
    webService.trimEnd(),
    engineService.trimEnd(),
    langfuseService.trimEnd(),
    mcpService.trimEnd(),
    caddyService.trimEnd(),
    volumes,
  ]
    .filter(Boolean)
    .join('\n')
}

function buildDependsOn(managedDb: boolean, managedRedis: boolean): string {
  const deps: string[] = []
  if (managedDb) deps.push('postgres')
  if (managedRedis) deps.push('redis')
  if (deps.length === 0) return ''
  return (
    '\n    depends_on:\n' +
    deps.map((d) => `      ${d}:\n        condition: service_healthy`).join('\n')
  )
}

function buildVolumes(managedDb: boolean, managedRedis: boolean): string {
  const vols: string[] = []
  if (managedDb) vols.push('  postgres_data:')
  if (managedRedis) vols.push('  redis_data:')
  vols.push('  caddy_data:')
  vols.push('  caddy_config:')
  return '\nvolumes:\n' + vols.join('\n')
}
