export interface EngineEnvConfig {
  databaseUrl: string
  redisUrl: string
  sfdcClientId: string
  sfdcClientSecret: string
  sfdcLoginUrl: string
  engineWebhookSecret: string
  enginePort?: number
  logLevel?: string
}

export function renderEnvEngine(c: EngineEnvConfig): string {
  return [
    `# Lead Routing — Engine Environment`,
    `# Generated by lead-routing CLI on ${new Date().toISOString()}`,
    ``,
    `# Server`,
    `ENGINE_PORT=${c.enginePort ?? 3001}`,
    `LOG_LEVEL=${c.logLevel ?? 'info'}`,
    `NODE_ENV=production`,
    ``,
    `# Database`,
    `DATABASE_URL=${c.databaseUrl}`,
    ``,
    `# Redis`,
    `REDIS_URL=${c.redisUrl}`,
    ``,
    `# Salesforce OAuth`,
    `SFDC_CLIENT_ID=${c.sfdcClientId}`,
    `SFDC_CLIENT_SECRET=${c.sfdcClientSecret}`,
    `SFDC_LOGIN_URL=${c.sfdcLoginUrl}`,
    ``,
    `# Webhook`,
    `ENGINE_WEBHOOK_SECRET=${c.engineWebhookSecret}`,
  ].join('\n')
}
