export interface EngineEnvConfig {
  databaseUrl: string
  redisUrl: string
  engineWebhookSecret: string
  internalApiKey: string
  enginePort?: number
  logLevel?: string
}

export function renderEnvEngine(c: EngineEnvConfig): string {
  return [
    `# Lead Routing — Engine Environment`,
    `# Generated by lead-routing CLI on ${new Date().toISOString()}`,
    ``,
    `# Server`,
    `ENGINE_PORT=${c.enginePort ?? 3001}`,
    `LOG_LEVEL=${c.logLevel ?? 'info'}`,
    `NODE_ENV=production`,
    ``,
    `# Database`,
    `DATABASE_URL=${c.databaseUrl}`,
    ``,
    `# Redis`,
    `REDIS_URL=${c.redisUrl}`,
    ``,
    `# Webhook`,
    `ENGINE_WEBHOOK_SECRET=${c.engineWebhookSecret}`,
    ``,
    `# Internal API key (Bearer token for analytics endpoints)`,
    `INTERNAL_API_KEY=${c.internalApiKey}`,
  ].join('\n')
}
