export interface EngineEnvConfig {
  databaseUrl: string
  redisUrl: string
  engineWebhookSecret: string
  internalApiKey: string
  enginePort?: number
  logLevel?: string
  licenseKey?: string
  licenseTier: string
  crmType?: 'salesforce' | 'hubspot'
  hubspotClientId?: string
  hubspotClientSecret?: string
}

export function renderEnvEngine(c: EngineEnvConfig): string {
  return [
    `# Lead Routing — Engine Environment`,
    `# Generated by lead-routing CLI on ${new Date().toISOString()}`,
    ``,
    `# Server`,
    `ENGINE_PORT=${c.enginePort ?? 3001}`,
    `LOG_LEVEL=${c.logLevel ?? 'info'}`,
    `NODE_ENV=production`,
    ``,
    `# Database`,
    `DATABASE_URL=${c.databaseUrl}`,
    ``,
    `# Redis`,
    `REDIS_URL=${c.redisUrl}`,
    ``,
    `# Webhook`,
    `ENGINE_WEBHOOK_SECRET=${c.engineWebhookSecret}`,
    ``,
    `# Internal API key (Bearer token for analytics endpoints)`,
    `INTERNAL_API_KEY=${c.internalApiKey}`,
    ``,
    `# License`,
    `LICENSE_KEY=${c.licenseKey ?? ''}`,
    `LICENSE_TIER=${c.licenseTier}`,
    `LICENSE_API_URL=https://lead-routing-license.artyagi2011.workers.dev`,
    ...(c.crmType === 'hubspot'
      ? [
          ``,
          `# HubSpot`,
          `HUBSPOT_CLIENT_ID=${c.hubspotClientId ?? ''}`,
          `HUBSPOT_CLIENT_SECRET=${c.hubspotClientSecret ?? ''}`,
        ]
      : []),
  ].join('\n')
}
