export interface WebEnvConfig {
  appUrl: string
  engineUrl: string        // Docker-internal: http://engine:3001
  publicEngineUrl: string  // Public HTTPS URL — used by pushSettings → Salesforce
  databaseUrl: string
  redisUrl: string
  sessionSecret: string
  engineWebhookSecret: string
  adminSecret: string
  adminEmail: string
  adminPassword: string
  internalApiKey: string
  resendApiKey?: string
  feedbackToEmail?: string
}

export function renderEnvWeb(c: WebEnvConfig): string {
  return [
    `# Lead Routing — Web App Environment`,
    `# Generated by lead-routing CLI on ${new Date().toISOString()}`,
    ``,
    `# App`,
    `APP_URL=${c.appUrl}`,
    `NODE_ENV=production`,
    ``,
    `# Engine`,
    `ENGINE_URL=${c.engineUrl}`,
    `PUBLIC_ENGINE_URL=${c.publicEngineUrl}`,
    `ENGINE_WEBHOOK_SECRET=${c.engineWebhookSecret}`,
    ``,
    `# Database`,
    `DATABASE_URL=${c.databaseUrl}`,
    ``,
    `# Redis`,
    `REDIS_URL=${c.redisUrl}`,
    ``,
    `# Session`,
    `SESSION_SECRET=${c.sessionSecret}`,
    ``,
    `# Admin`,
    `ADMIN_SECRET=${c.adminSecret}`,
    `ADMIN_EMAIL=${c.adminEmail}`,
    `ADMIN_PASSWORD=${c.adminPassword}`,
    ``,
    `# Internal API key (shared with engine for analytics)`,
    `INTERNAL_API_KEY=${c.internalApiKey}`,
    ``,
    `# Email (optional)`,
    `RESEND_API_KEY=${c.resendApiKey ?? ''}`,
    `FEEDBACK_TO_EMAIL=${c.feedbackToEmail ?? ''}`,
  ].join('\n')
}
