export interface WebEnvConfig {
  appUrl: string
  engineUrl: string        // Docker-internal: http://engine:3001
  publicEngineUrl: string  // Public HTTPS URL — used by pushSettings → Salesforce
  databaseUrl: string
  redisUrl: string
  sessionSecret: string
  engineWebhookSecret: string
  adminEmail: string
  adminPassword: string
  internalApiKey: string
  resendApiKey?: string
  feedbackToEmail?: string
  licenseKey?: string
  licenseTier: string
  crmType?: 'salesforce' | 'hubspot'
  hubspotClientId?: string
  hubspotClientSecret?: string
  hubspotAppId?: string
}

export function renderEnvWeb(c: WebEnvConfig): string {
  return [
    `# Lead Routing — Web App Environment`,
    `# Generated by lead-routing CLI on ${new Date().toISOString()}`,
    ``,
    `# App`,
    `APP_URL=${c.appUrl}`,
    `NODE_ENV=production`,
    ``,
    `# Engine`,
    `ENGINE_URL=${c.engineUrl}`,
    `PUBLIC_ENGINE_URL=${c.publicEngineUrl}`,
    `ENGINE_WEBHOOK_SECRET=${c.engineWebhookSecret}`,
    ``,
    `# Database`,
    `DATABASE_URL=${c.databaseUrl}`,
    ``,
    `# Redis`,
    `REDIS_URL=${c.redisUrl}`,
    ``,
    `# Session`,
    `SESSION_SECRET=${c.sessionSecret}`,
    ``,
    `# Admin`,
    `ADMIN_EMAIL=${c.adminEmail}`,
    `ADMIN_PASSWORD=${c.adminPassword}`,
    ``,
    `# Internal API key (shared with engine for analytics)`,
    `INTERNAL_API_KEY=${c.internalApiKey}`,
    ``,
    `# License`,
    `LICENSE_KEY=${c.licenseKey ?? ''}`,
    `LICENSE_TIER=${c.licenseTier}`,
    `LICENSE_API_URL=https://lead-routing-license.artyagi2011.workers.dev`,
    ``,
    `# Email (optional)`,
    `RESEND_API_KEY=${c.resendApiKey ?? ''}`,
    `FEEDBACK_TO_EMAIL=${c.feedbackToEmail ?? ''}`,
    ``,
    `# CRM`,
    `CRM_TYPE=${c.crmType ?? 'salesforce'}`,
    ...(c.crmType === 'hubspot'
      ? [
          ``,
          `# HubSpot`,
          `HUBSPOT_CLIENT_ID=${c.hubspotClientId ?? ''}`,
          `HUBSPOT_CLIENT_SECRET=${c.hubspotClientSecret ?? ''}`,
          `HUBSPOT_APP_ID=${c.hubspotAppId ?? ''}`,
          `HUBSPOT_REDIRECT_URI=${c.appUrl}/api/auth/hubspot/callback`,
        ]
      : []),
  ].join('\n')
}
