/**
 * Full Salesforce onboarding flow run from the CLI after VPS deploy succeeds.
 *
 * Replaces the previous "open the web app and click around" UX. After this
 * step completes the user has:
 *   - Managed package installed in their org
 *   - OAuth tokens stored in the web app (via the cli-auth bridge)
 *   - Routing_Settings__c, Remote Site Settings, Named Credential deployed
 *   - LEAD field schema synced (CONTACT + ACCOUNT on Pro tier)
 *   - Optionally: a test event sent + onboardingDone flag flipped
 *
 * Idempotent — safe to re-run. Detects an already-connected org via
 * `/api/setup/status` (when sfdcOrgId is known) and skips the OAuth bridge.
 */

import { exec } from 'node:child_process'
import { platform } from 'node:os'
import { confirm, isCancel, log, note, spinner } from '@clack/prompts'
import chalk from 'chalk'
import { loginViaAppBridge, sfdcDeployInline } from './sfdc-deploy-inline.js'
import {
  syncFields,
  type FieldSyncResult,
  type SfdcObjectType,
} from '../utils/field-sync-client.js'

const MANAGED_PACKAGE_INSTALL_URL =
  'https://login.salesforce.com/packaging/installPackage.apexp?p0=04tgL000000CTnp'

export interface SfdcOnboardParams {
  appUrl: string
  engineUrl: string
  /** Bearer token for /api/fields/sync, /api/setup/* — pulled from
   *  ~/.lead-routing/credentials.json or generated by `init`. */
  apiToken: string
  /** Webhook secret for HMAC validation — written to Routing_Settings__c. */
  webhookSecret?: string
  /** Org alias, used by `sfdcDeployInline` for log messages. */
  orgAlias?: string
  /** Where the patched package is staged. Default: tmpdir. */
  installDir?: string
  /** Free-tier installs cannot sync CONTACT/ACCOUNT. */
  licenseTier?: 'free' | 'pro'
  /** Skip the optional test-event call. */
  skipTestEvent?: boolean
}

export interface SfdcOnboardResult {
  sfdcOrgId?: string
  fieldsSynced: Partial<Record<SfdcObjectType, FieldSyncResult>>
  onboardingDone: boolean
  testEventSent: boolean
}

function openBrowser(url: string): void {
  const cmd = platform() === 'darwin' ? 'open' : platform() === 'win32' ? 'start' : 'xdg-open'
  try {
    exec(`${cmd} ${JSON.stringify(url)}`)
  } catch {
    // No-op — URL is also printed to the console.
  }
}

function trim(url: string): string {
  return url.replace(/\/+$/, '')
}

/**
 * Check whether a Salesforce org is already connected to this Lead Routing
 * deployment, returning `{ connected, onboardingDone }` when known. Returns
 * `null` if the endpoint is unreachable or the sfdcOrgId is unknown.
 */
async function fetchSetupStatus(
  appUrl: string,
  sfdcOrgId: string | undefined,
  apiToken: string
): Promise<{ connected: boolean; onboardingDone: boolean } | null> {
  if (!sfdcOrgId) return null
  try {
    const url = `${trim(appUrl)}/api/setup/status?sfdcOrgId=${encodeURIComponent(sfdcOrgId)}`
    const res = await fetch(url, {
      headers: { Authorization: `Bearer ${apiToken}` },
      signal: AbortSignal.timeout(10_000),
    })
    if (!res.ok) return null
    return (await res.json()) as { connected: boolean; onboardingDone: boolean }
  } catch {
    return null
  }
}

/**
 * Trigger the optional test-event endpoint. Failure is non-fatal and only
 * surfaced as a warning.
 */
async function sendTestEvent(
  appUrl: string,
  apiToken: string,
  sfdcOrgId?: string
): Promise<{ ok: boolean; error?: string }> {
  try {
    const headers: Record<string, string> = {
      Authorization: `Bearer ${apiToken}`,
      'Content-Type': 'application/json',
    }
    if (sfdcOrgId) headers['X-Sfdc-Org-Id'] = sfdcOrgId

    const res = await fetch(`${trim(appUrl)}/api/setup/test-event`, {
      method: 'POST',
      headers,
      body: '{}',
      signal: AbortSignal.timeout(20_000),
    })

    if (res.ok) return { ok: true }
    if (res.status === 404) return { ok: false, error: 'endpoint not deployed yet' }
    const text = await res.text().catch(() => '')
    return { ok: false, error: `HTTP ${res.status} ${text || res.statusText}` }
  } catch (err) {
    return {
      ok: false,
      error: err instanceof Error ? err.message : String(err),
    }
  }
}

/** Mark onboarding complete via /api/setup/onboarding-done. */
async function markOnboardingDone(
  appUrl: string,
  apiToken: string,
  sfdcOrgId?: string
): Promise<{ ok: boolean; error?: string }> {
  try {
    const headers: Record<string, string> = {
      Authorization: `Bearer ${apiToken}`,
      'Content-Type': 'application/json',
    }
    if (sfdcOrgId) headers['X-Sfdc-Org-Id'] = sfdcOrgId

    const res = await fetch(`${trim(appUrl)}/api/setup/onboarding-done`, {
      method: 'POST',
      headers,
      body: '{}',
      signal: AbortSignal.timeout(15_000),
    })

    if (res.ok) return { ok: true }
    const text = await res.text().catch(() => '')
    return { ok: false, error: `HTTP ${res.status} ${text || res.statusText}` }
  } catch (err) {
    return {
      ok: false,
      error: err instanceof Error ? err.message : String(err),
    }
  }
}

/**
 * Run the full Salesforce onboarding flow from the CLI.
 *
 * The function is intentionally chatty — every external call is wrapped in a
 * spinner and logs both success and failure. Returns a structured result so
 * callers (init.ts) can render a final summary.
 */
export async function sfdcOnboard(params: SfdcOnboardParams): Promise<SfdcOnboardResult> {
  const {
    appUrl,
    engineUrl,
    apiToken,
    webhookSecret,
    orgAlias = 'lead-routing',
    installDir,
    licenseTier = 'free',
    skipTestEvent = false,
  } = params

  const result: SfdcOnboardResult = {
    fieldsSynced: {},
    onboardingDone: false,
    testEventSent: false,
  }

  // ── 1. Managed package install prompt ──────────────────────────────────────
  note(
    'The Lead Router managed package installs the Connected App,\n' +
      'triggers, and custom objects in your Salesforce org.\n\n' +
      `Install URL: ${chalk.cyan(MANAGED_PACKAGE_INSTALL_URL)}`,
    'Salesforce Package'
  )
  log.info('Opening Salesforce package install URL in your browser…')
  openBrowser(MANAGED_PACKAGE_INSTALL_URL)
  log.info(chalk.dim("If the browser didn't open, copy and paste the URL above."))

  const installed = await confirm({
    message: 'Have you installed the package? (Click "Install for All Users")',
    initialValue: false,
  })
  if (isCancel(installed)) {
    throw new Error('Onboarding cancelled by user.')
  }
  if (!installed) {
    log.warn(
      'Skipping the rest of Salesforce onboarding — routing will not work until the package is installed.'
    )
    return result
  }
  log.success('Salesforce package installed')

  // ── 2. OAuth via app bridge ────────────────────────────────────────────────
  let accessToken: string
  let instanceUrl: string
  try {
    const auth = await loginViaAppBridge(appUrl, apiToken)
    accessToken = auth.accessToken
    instanceUrl = auth.instanceUrl
    result.sfdcOrgId = auth.sfdcOrgId
  } catch (err) {
    throw new Error(
      `Salesforce OAuth via the web app bridge failed: ${err instanceof Error ? err.message : String(err)}`
    )
  }

  // ── 3. Idempotency check — skip deploy if already done ─────────────────────
  const status = await fetchSetupStatus(appUrl, result.sfdcOrgId, apiToken)
  let needsDeploy = true
  if (status?.connected && status.onboardingDone) {
    log.info('This org is already connected and onboarded — skipping deploy step.')
    needsDeploy = false
  }

  // ── 4. Deploy Routing_Settings__c, Remote Sites, Named Credential ──────────
  if (needsDeploy) {
    try {
      await sfdcDeployInline({
        appUrl,
        engineUrl,
        orgAlias,
        installDir,
        webhookSecret,
        auth: { accessToken, instanceUrl },
      })
    } catch (err) {
      // Deploy failure is fatal — without it the rest of the org config is
      // missing and routing won't work.
      throw new Error(
        `Salesforce package deploy failed: ${err instanceof Error ? err.message : String(err)}`
      )
    }
  }

  // ── 5. Sync field schemas ──────────────────────────────────────────────────
  const objects: SfdcObjectType[] = ['LEAD', 'CONTACT', 'ACCOUNT']
  for (const obj of objects) {
    if (obj !== 'LEAD' && licenseTier === 'free') {
      log.info(
        `Skipping ${obj} field sync — Free tier only allows LEAD. Upgrade to Pro to enable.`
      )
      result.fieldsSynced[obj] = { ok: true, skipped: true }
      continue
    }

    const s = spinner()
    s.start(`Syncing ${obj} field schema…`)
    const r = await syncFields(appUrl, obj, {
      apiToken,
      sfdcOrgId: result.sfdcOrgId,
    })
    result.fieldsSynced[obj] = r

    if (r.skipped) {
      s.stop(`${obj} skipped (license tier)`)
    } else if (r.ok) {
      s.stop(`${obj} fields synced (${r.synced ?? 0})`)
    } else {
      s.stop(`${obj} field sync failed`)
      log.warn(r.error ?? 'unknown error')
      // Don't throw — continue with the remaining objects so we surface every
      // failure at once instead of forcing the user to re-run.
    }
  }

  // ── 6. Optional test event ─────────────────────────────────────────────────
  if (!skipTestEvent) {
    const s = spinner()
    s.start('Sending test event to engine…')
    const t = await sendTestEvent(appUrl, apiToken, result.sfdcOrgId)
    if (t.ok) {
      s.stop('Test event sent')
      result.testEventSent = true
    } else {
      s.stop('Test event skipped')
      log.warn(`Test event not sent: ${t.error ?? 'unknown error'}`)
    }
  }

  // ── 7. Mark onboarding complete ────────────────────────────────────────────
  const s = spinner()
  s.start('Marking onboarding complete…')
  const done = await markOnboardingDone(appUrl, apiToken, result.sfdcOrgId)
  if (done.ok) {
    s.stop('Onboarding complete')
    result.onboardingDone = true
  } else {
    s.stop('Could not mark onboarding done')
    log.warn(
      `Failed to call /api/setup/onboarding-done: ${done.error ?? 'unknown'}.\n` +
        `You can complete this manually from ${appUrl}/integrations/salesforce.`
    )
  }

  return result
}
