name = "lead-routing-license"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[[d1_databases]]
binding = "DB"
database_name = "lead-routing-licenses"
database_id = "917acf95-2b58-4f11-8fc8-0d0c02db077f"

[vars]
STRIPE_SECRET_KEY = "sk_test_51TBKnpLC6aUVPcRdsTCnYKgKkPXE0W9pGIdLx5Ue2u75syhflhxIuoVC6zhBPgzDjg6eZEPjBP9QQoLf6RmL1ukF00ALfsZSPx"
STRIPE_WEBHOOK_SECRET = "whsec_el0ZwTdEUsbXlSbDLjObENeHCZHMMx6r"
STRIPE_PRICE_ID = "price_1TES71LC6aUVPcRdnWJpJjaU"
RESEND_API_KEY = "re_inAj8vmB_5R9Rg6BKJGSwK5b6hg2btJd1"
ED25519_PRIVATE_KEY = "MC4CAQAwBQYDK2VwBCIEINXrpazTxLM2nfpqgDz18F62MQnpzWHSYcizUp4gsngt"
ED25519_PUBLIC_KEY = "N+pGcsgBz8l45heKgwks1vcCMKrakYjE4mxaAPCXrXY="
ADMIN_SECRET = "lr-admin-2026-change-me-in-production"
